language: java
jdk:
- openjdk8
addons:
    apt:
	addons:
      packages:
        ant
 sonarcloud:
 organization: praysc
 token:
 secure: b410a26275e6f0e51f082b33ef53db8ca9820c72
script: 
- ant build 
- sonar-scanner
